### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by tomkallo** [Bw3ll/ShellWasp#1]
Cool project guys. Win10, Python3.exe is sufficient with:

`pip install metame keystone`

Otherwise errors abound

**Comment by Bw3ll** [comment]
Hey,
Thank you for the issue.  I went ahead and created a setup.py file, that will take care of that and colorama, and I updated the readme as well. I use keystone to generate the bytes for the Assembly code, but I don't display it currently. I did before, but I didn't want people to think it was "complete." I may reenable it as an optional setting later.

The main way to do keystone-engine is **pip install keystone-engine**. I am guessing that metame is an alternative way. I have also put that on the readme.

I apologize for not having the incomplete information. I was rushing to get that uploaded, and I had not had a chance to write it. Please let me know if you run into any other issues.

**Comment by Bw3ll** [comment]
Closing issue. Feel free to start a new issue if something comes up.
